### ISSUE TITLE
unable to specify return type of any1?

### ISSUE THREAD

**Issue by vbarua** [substrait-io/substrait-java#169]
Given a scalar function definition with nullable `any` return, the following definition works:
```
scalar_functions:
- name: "array_index"
    description: "returns the element in the array at index, or NULL if index is out of bounds"
    impls:
      - args:
          - name: array
            value: list<any>
          - name: index
            value: i64
        return: any?
```

whilst the equivalent definition

```
%YAML 1.2
---
scalar_functions:
- name: "array_index"
    description: "returns the element in the array at index, or NULL if index is out of bounds"
    impls:
      - args:
          - name: array
            value: list<any1>
          - name: index
            value: i64
        return: any1?
```

fails with
```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Unable to parse string any1?
```
